# Generated by Django 4.2.4 on 2023-11-24 21:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='auction_listing',
            name='image',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auction_listing',
            name='start_bid',
            field=models.FloatField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auction_listing',
            name='category',
            field=models.CharField(choices=[('toys', 'Toys'), ('fashion', 'Fashion'), ('car', 'Car'), ('electronics', 'Electronics'), ('home', 'Home')], max_length=255),
        ),
    ]
