# Generated by Django 4.2.4 on 2023-12-26 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_comments_comment_comments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='listing',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='auctions.auction_listing'),
            preserve_default=False,
        ),
    ]
